# Generated by Django 2.2.5 on 2020-10-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('sjsuID', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('component', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
    ]
