# Generated by Django 3.1.2 on 2020-11-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201106_2248'),
        ('core', '0002_auto_20201108_1044'),
    ]

    operations = [
    ]
